// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgdiyUxrWoSfbVxKRN5fdvq83pGDpwhY',
    appId: '1:893294502156:web:fa28de3d10d9d8184c6929',
    messagingSenderId: '893294502156',
    projectId: 'fcm-services-d2195',
    authDomain: 'fcm-services-d2195.firebaseapp.com',
    storageBucket: 'fcm-services-d2195.appspot.com',
    measurementId: 'G-FD6NR8PS6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4g1MK33bS4l1yDqCAVBunixUHcZ4HwVM',
    appId: '1:893294502156:android:cf52f71a502671e94c6929',
    messagingSenderId: '893294502156',
    projectId: 'fcm-services-d2195',
    storageBucket: 'fcm-services-d2195.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-alvnffMJHAmEBR82WrcOJ0-5nffxfs',
    appId: '1:893294502156:ios:86f21526c67d376a4c6929',
    messagingSenderId: '893294502156',
    projectId: 'fcm-services-d2195',
    storageBucket: 'fcm-services-d2195.appspot.com',
    iosClientId:
        '893294502156-2hmrv14bjovf3ir06ano2tm4k0li1vme.apps.googleusercontent.com',
    iosBundleId: 'com.mindpalace.todo',
  );

  static const String vapidKey =
      'BPSJNMmaP1MENq1vcTjwPxOAnMtCtFe0cTe2mQNGT0v4DLIQ1VCu4Jqc7fpe3M_0CQM0XdUBxDoYfz7kHVKfCA4';
}
